# Generated by Django 4.2.14 on 2024-07-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="default_image.jpg", upload_to="products", verbose_name="Imagen"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("unitario", "Precio Unitario"),
                    ("media-doc", "Media Docena"),
                    ("docena", "Docena"),
                    ("por-kilo", "kilo"),
                ],
                default="unitario",
                max_length=9,
                verbose_name="Tipo de precio",
            ),
        ),
    ]
